export interface Order {
  id: number;
  orderNumber: string;
  weight: number;
  laundryFee: number;
  total: number;
  isPaid: boolean;
  orderStatus: OrderStatus;
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date;
  outletId: number;
  userId: number;
}

export enum OrderStatus {
  WAITING_FOR_PICKUP_DRIVER = "WAITING_FOR_PICKUP_DRIVER",
  PICKUP_ON_THE_WAY_TO_CUSTOMER = "PICKUP_ON_THE_WAY_TO_CUSTOMER",
  PICKUP_ON_THE_WAY_TO_OUTLET = "PICKUP_ON_THE_WAY_TO_OUTLET",
  ARRIVED_AT_OUTLET = "ARRIVED_AT_OUTLET",
  READY_FOR_WASHING = "READY_FOR_WASHING",
  BEING_WASHED = "BEING_WASHED",
  WASHING_COMPLETED = "WASHING_COMPLETED",
  BEING_IRONED = "BEING_IRONED",
  IRONING_COMPLETED = "IRONING_COMPLETED",
  BEING_PACKED = "BEING_PACKED",
  AWAITING_PAYMENT = "AWAITING_PAYMENT",
  READY_FOR_DELIVERY = "READY_FOR_DELIVERY",
  WAITING_FOR_DELIVERY_DRIVER = "WAITING_FOR_DELIVERY_DRIVER",
  BEING_DELIVERED_TO_CUSTOMER = "BEING_DELIVERED_TO_CUSTOMER",
  RECEIVED_BY_CUSTOMER = "RECEIVED_BY_CUSTOMER",
}
